---
title: "Final"
author: "Roberta"
date: "16/01/2021"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(dplyr)
library(sf)
library(stringr)
library(tmap)
library(classInt)
library(broom)
library(corrplot)
library(spdep)
```

```{r message=FALSE, warning=FALSE}
CB = read_csv('./certified businesses.csv')
sf_boston = sf::read_sf('./ZIP_Codes-shp/ZIP_Codes.shp')
pop = read_csv('./population_by_zip.csv')
```


```{r message=FALSE, warning=FALSE}
# problem with one zip code which is actually divided into 4 polygons, 
plot(sf_boston[sf_boston$ZIP5 == '02467',]['ZIP5'])

zip2467 = st_combine(sf_boston[sf_boston$ZIP5 == '02467',])
zip_rest = sf_boston[!sf_boston$ZIP5 == '02467',]

# create sf object from combined polygons
sf_object = zip2467 %>% st_sf %>% st_cast

# add all the rows
sf_object$OBJECTID = 37
sf_object$ZIP5 = '02467'
sf_object$ShapeSTAre = NA
sf_object$ShapeSTLen = NA

# join back together
zip_codes = rbind(zip_rest, sf_object, deparse.level = 1)
plot(zip_codes['ZIP5'])
```


```{r}
# Create lists
li1 = c('Boston', 'East Boston', 'South Boston')
li2 = c('WBE', 'MWBE')

# choose the rows that fits the lists
CB1 = CB[CB$city %in% li1,]

# create column with gender
CB1$sex = 'male'
CB1$sex[which(CB1$mbe_wbe_cert %in% li2)] = 'female'

CB2 = CB1 %>% dplyr::select(sex, zipcode)

female = CB2[CB2$sex == 'female',]
female = female[!is.na(female$zipcode),]

# fix the zip codes in the rows 28 and 45
female$zipcode[45] = '02127'
female$zipcode[28] = '02113'

#male data set
male = CB2[CB2$sex == 'male',]

```

```{r}
grouped_female = female %>% 
   dplyr::select(zipcode) %>% 
   group_by(zipcode) %>% 
   summarise(count_female = n() ) %>%
   mutate(freq_female = count_female / sum(count_female)) 

grouped_male = male %>% 
   dplyr::select(zipcode) %>% 
   group_by(zipcode) %>% 
   summarise(count_male = n() ) %>% 
   mutate(freq_male = count_male / sum(count_male))

knitr::kable(head(grouped_female))
```

```{r message=FALSE, warning=FALSE}
#merging 
data = merge(zip_codes, grouped_male, how = 'left', by.x = "ZIP5", by.y = "zipcode",all.x= TRUE)
data = merge(data, grouped_female, how = 'left', by.x = "ZIP5", by.y = "zipcode" ,all.x= TRUE)
data = merge(data, pop, how = 'left', by.x = "ZIP5", by.y = "Zip Code" ,all.x= TRUE)

data$diff = abs(data$count_female - data$count_male)
data$diff_fr = abs(data$freq_female - data$freq_male)
data$female_buss_per_capita = (data$count_female/(data$Population_estimate_2019/1000))

data$male_buss_per_capita = (data$count_male/(data$Population_estimate_2019/1000))
```

```{r message=FALSE, warning=FALSE}
plot(data["freq_male"], breaks = "quantile", nbreaks = 7)
plot(data["freq_female"], breaks = "quantile", nbreaks = 7)
plot(data["diff_fr"], breaks = "quantile", nbreaks = 7)
```



```{r}
##tmap
tm_shape(data)+
  tm_fill("freq_male",
          n = 4,
          style = "quantile", 
          palette = "Blues",
          legend.hist = TRUE,) +
   tm_compass(type="8star", size = 2) +
  tm_scale_bar(width = 0.15) +
  tm_borders(alpha = 0.5)

tm_shape(data)+
  tm_fill("freq_female",
          n = 4,
          style = "quantile", 
          palette = "Reds",
          legend.hist = TRUE,) +
   tm_compass(type="8star", size = 2) +
  tm_scale_bar(width = 0.15) +
  tm_borders(alpha = 0.5)

tm_shape(data)+
  tm_fill("diff_fr",
          n = 4,
          style = "quantile", 
          palette = "Greens",
          legend.hist = TRUE,) +
   tm_compass(type="8star", size = 2) +
  tm_scale_bar(width = 0.15) +
  tm_borders(alpha = 0.5) 

tm_shape(data)+
  tm_fill("female_buss_per_capita",
          n = 4,
          style = "quantile", 
          palette = "Oranges",
          legend.hist = TRUE,) +
   tm_compass(type="8star", size = 2) +
  tm_scale_bar(width = 0.15) +
  tm_borders(alpha = 0.5) 

tm_shape(data)+
  tm_fill("male_buss_per_capita",
          n = 4,
          style = "quantile", 
          palette = "Blues",
          legend.hist = TRUE,) +
   tm_compass(type="8star", size = 2) +
  tm_scale_bar(width = 0.15) +
  tm_borders(alpha = 0.5) 
```


```{r}
#Kernel density
plot(density(data$freq_male, na.rm = TRUE))
plot(density(data$freq_female, na.rm = TRUE))
plot(density(data$diff_fr, na.rm = TRUE))
plot(density(data$female_buss_per_capita, na.rm = TRUE))
plot(density(data$male_buss_per_capita, na.rm = TRUE))
```


```{r}
##including shop data for Boston
shops = read_sf('./boston/shop_point.geojson')

```

```{r}

shops = shops[,c('shop','geometry')]

# make a spatial join to get the zip information to shops
x = st_join(shops, zip_codes, left= TRUE)

# aggregate the shops by zip codes
grouped_shops = x %>% 
   st_drop_geometry() %>%
   dplyr::select(ZIP5) %>% 
   group_by(ZIP5) %>% 
   summarise(count_shop = n() ) %>% 
   mutate(freq_shop = count_shop / sum(count_shop)) # calculate new column that gives frequency of businesses

# join to the data
data = merge(data, grouped_shops, how = 'left', by = "ZIP5" ,all.x= TRUE)

# calculate per capita
data$shop_per_capita = (data$count_shop/(data$Population_estimate_2019/1000))

knitr::kable(head(data))
```


```{r fig.width=15, fig.height=15, echo=FALSE}
# Shop point data map
#install.packages("ggspatial")

library(ggspatial)
ggplot(data = zip_codes) +
   geom_sf( aes( fill =ZIP5)) +  
   geom_sf(data = shops, size = 2, color = 'black') +
   theme_void() +
  annotation_scale() + 
  annotation_north_arrow()


```
```{r}
sum(grouped_shops$count_shop)
```
```{r fig.width=15, fig.height=15, echo=FALSE}
#map with zipcode colours removed

ggplot(data = zip_codes) +
   geom_sf( ) +  
   geom_sf(data = shops, size = 2, color = 'blue') +
   theme_void() +
  annotation_scale() + 
  annotation_north_arrow()
```

```{r}
# frequancy density maps 
tm_shape(data)+
  tm_fill("freq_female",
          n = 4,
          style = "quantile", 
          palette = "Purples",
          legend.hist = TRUE,) +
   tm_compass(type="8star", size = 2) +
  tm_scale_bar(width = 0.15) +
  tm_borders(alpha = 0.5) 

tm_shape(data)+
  tm_fill("freq_male",
          n = 4,
          style = "quantile", 
          palette = "Blues",
          legend.hist = TRUE,) +
   tm_compass(type="8star", size = 2) +
  tm_scale_bar(width = 0.15) +
  tm_borders(alpha = 0.5)

tm_shape(data)+
  tm_fill("freq_shop",
          n = 4,
          style = "quantile", 
          palette = "Oranges",
          legend.hist = TRUE,) +
   tm_compass(type="8star", size = 2) +
  tm_scale_bar(width = 0.15) +
  tm_borders(alpha = 0.5)
```



```{r}
# indexing

data[5,4] 
grouped_female[5, c( 'count_female', 'zipcode')] 

# logic

grouped_female$zipcode == '02108'

grouped_female[grouped_female$zipcode == '02108' | grouped_female$zipcode == '02109',] # & = and , | = OR

# using lists

list1 = c('02108', '02108')

grouped_female[grouped_female = list1,]

data[is.na(data)] = 0
```



```{r}
q1 <- qplot(x = `freq_female`, 
           y = `freq_male`, 
           data=data)

q2 <- qplot(x = `freq_female`, 
           y = `freq_shop`, 
           data=data)

q3 <- qplot(x = `freq_male`, 
           y = `freq_shop`, 
           data=data)

#plot with a regression line - note, added some jitter here as the x-scale is rounded
q1 + stat_smooth(method="lm", se=FALSE, size=1) + 
  geom_jitter()
#plot with a regression line - note, added some jitter here as the x-scale is rounded
q2 + stat_smooth(method="lm", se=FALSE, size=1) + 
  geom_jitter()

q3 + stat_smooth(method="lm", se=FALSE, size=1) + 
  geom_jitter()
```

```{r}

plot(density(data$freq_female, na.rm = TRUE))
plot(density(data$freq_male, na.rm = TRUE))
plot(density(data$freq_shop, na.rm = TRUE))
plot(density(data$Population_estimate_2019))

#Log transformation 

plot(density(log(data$freq_female), na.rm = TRUE))   
plot(density(log(data$freq_male), na.rm = TRUE))
plot(density(log(data$freq_shop), na.rm = TRUE))
plot(density(log(data$Population_estimate_2019)))
```


```{r}
#Regresion models
model1 = lm(freq_female ~ freq_shop + Population_estimate_2019, data = data)
model2 = lm(freq_male ~ freq_shop + Population_estimate_2019, data = data)
summary(model1)
summary(model2)

```

```{r}
#log transformation
model1 = lm(log1p(freq_female) ~ log1p(freq_shop) + Population_estimate_2019, data = data)
model2 = lm(log1p(freq_male) ~ log1p(freq_shop) + Population_estimate_2019, data = data)      
summary(model1)
summary(model2)


```

```{r}
plot(density(model1$residuals))
plot(density(model2$residuals))   
```
```{r}

# Multicolinearity

library(corrplot)
d = data[,c('freq_male','freq_female','freq_shop','Population_estimate_2019' )]
st_geometry(d) <- NULL

M<-cor(d,  use = "pairwise.complete.obs")
corrplot(M)
```


```{r}
# Spatial autocorrelation
##create extra dataset
data2 = data %>% 
   dplyr::select(ZIP5, count_female, count_male, count_shop, geometry) %>% 
   mutate(area = st_area(.)) %>% 
   mutate(density_shop = count_shop/area) %>% 
   mutate(density_female = count_female/area) %>% 
   mutate(density_male = count_male/area) 

# For the spatial weights - substitute the NA with 0
data2$density_male[is.na(data2$density_male)] = 0
data2$density_female[is.na(data2$density_female)] = 0
data2$density_shop[is.na(data2$density_shop)] = 0
```


``` {r}
# calculate the centroids
coordsW <- data2 %>%
  st_centroid() %>%
  st_geometry()
  
plot(coordsW,axes=TRUE)

#Coerce sf into sp
data3 <- as(data2, "Spatial")
#Generate list of neighbors using the Queen criteria
w <- poly2nb(data3, row.names=data2$ZIP5, queen=T,  snap = 0.03)
#Generate list with weights using row standardisation
ww <-  nb2listw(w, style='W', zero.policy=TRUE)

#plot them
plot(w, st_geometry(coordsW), col="red")
#add a map underneath
plot(data$geometry, add=T)
```

```{r}

# include spatial lag for desired variable into data set
data3$lag_female = lag.listw(ww, as.numeric(data3$density_female))
      
# Moran's I female data
moran.test(as.numeric(data2$density_female),ww) 

moran.plot(as.numeric(data2$density_female), ww)
```
```{r}

# Moran's I male data
data3$lag_male = lag.listw(ww, as.numeric(data3$density_female))

moran.test(as.numeric(data2$density_male),ww)

moran.plot(as.numeric(data2$density_male), ww)
```

```{r}
#Spatial Autocorrelation 
#LISA female data
#use the local Moran function to generate I for each ward in the city
lisa1 <- localmoran(as.numeric(data2$density_female), ww)
summary(lisa1)  

# get to polygon data
moran.map <- cbind(data3, lisa1)

# plot
tm_shape(moran.map) +
  tm_fill(col = "Ii",
          style = "quantile",
          title = "local moran statistic")         

```

```{r}
# plot LISA clusters female
quadrant <- vector(mode="numeric",length=nrow(lisa1))

# centers the variable of interest around its mean
centred_female <- as.numeric(data2$density_female) - mean(as.numeric(data2$density_female))

# centers the local Moran's around the mean
m.local <- lisa1[,1] - mean(lisa1[,1])    

# significance threshold
signif <- 0.1 

# builds a data quadrant
quadrant[centred_female >0 & m.local>0] <- 4  
quadrant[centred_female <0 & m.local<0] <- 1      
quadrant[centred_female <0 & m.local>0] <- 2
quadrant[centred_female >0 & m.local<0] <- 3
quadrant[lisa1[,5]>signif] <- 0   

# plot in r
brks <- c(0,1,2,3,4)
colors <- c("white","blue",rgb(0,0,1,alpha=0.4),rgb(1,0,0,alpha=0.4),"red")
plot(data3,border="lightgray",col=colors[findInterval(quadrant,brks,all.inside=FALSE)])
box()
legend("bottomleft", legend = c("insignificant","low-low","low-high","high-low","high-high"),
       fill=colors,bty="n")
```

```{r}
#plot male Lisa

lisa2 <- localmoran(as.numeric(data2$density_male), ww)
summary(lisa2)

# get to polygon data
moran.map <- cbind(data3, lisa2)

# plot
tm_shape(moran.map) +
  tm_fill(col = "Ii",
          style = "quantile",
          title = "local moran statistic")      
```


```{r} 
# plot LISA clusters MALE

quadrant <- vector(mode="numeric",length=nrow(lisa2))

# centers the variable of interest around its mean
centred_male <- as.numeric(data2$density_male) - mean(as.numeric(data2$density_male))

# centers the local Moran's around the mean
m.local <- lisa2[,1] - mean(lisa2[,1])    

# significance threshold
signif <- 0.1 

# builds a data quadrant
quadrant[centred_male >0 & m.local>0] <- 4  
quadrant[centred_male <0 & m.local<0] <- 1      
quadrant[centred_male <0 & m.local>0] <- 2
quadrant[centred_male >0 & m.local<0] <- 3
quadrant[lisa2[,5]>signif] <- 0   

# plot in r
brks <- c(0,1,2,3,4)
colors <- c("white","blue",rgb(0,0,1,alpha=0.4),rgb(1,0,0,alpha=0.4),"red")
plot(data3,border="lightgray",col=colors[findInterval(quadrant,brks,all.inside=FALSE)])
box()
legend("bottomleft", legend = c("insignificant","low-low","low-high","high-low","high-high"),
       fill=colors,bty="n")
```

```{r}
# LISA  Shops data

lisa3 <- localmoran(as.numeric(data2$density_shop), ww)
summary(lisa3)


moran.map <- cbind(data3, lisa3)


tm_shape(moran.map) +
  tm_fill(col = "Ii",
          style = "quantile",
          title = "local moran statistic")  
```

```{r}
# plot LISA clusters shops

quadrant <- vector(mode="numeric",length=nrow(lisa3))

# centers the variable of interest around its mean
centred_shop <- as.numeric(data2$density_shop) - mean(as.numeric(data2$density_shop))

# centers the local Moran's around the mean
m.local <- lisa3[,1] - mean(lisa3[,1])    

# significance threshold
signif <- 0.1 

# builds a data quadrant
quadrant[centred_male >0 & m.local>0] <- 4  
quadrant[centred_male <0 & m.local<0] <- 1      
quadrant[centred_male <0 & m.local>0] <- 2
quadrant[centred_male >0 & m.local<0] <- 3
quadrant[lisa2[,5]>signif] <- 0   

# plot in r
brks <- c(0,1,2,3,4)
colors <- c("white","blue",rgb(0,0,1,alpha=0.4),rgb(1,0,0,alpha=0.4),"red")
plot(data3,border="lightgray",col=colors[findInterval(quadrant,brks,all.inside=FALSE)])
box()
legend("bottomleft", legend = c("insignificant","low-low","low-high","high-low","high-high"),
       fill=colors,bty="n")
```


[][]
